#!/usr/bin/env bash

link (){
if [ -e $1 ]; then
    if [ -e $2 ]; then
    rm $2
    fi

    ln -s $1 $2
fi
}

link ~/.dotfiles/.bashrc ~/.bashrc
link ~/.dotfiles/bin ~/bin
link ~/.dotfiles/.irssi ~/.irssi
link ~/.dotfiles/bin/byobu ~/.byobu/bin
link ~/.dotfiles/.config/terminator ~/.config/terminator
