#!/usr/bin/env bash

link (){
if [ -e $1 ]; then
    if [ -e $2 ]; then
        rm -r $2
    fi

    ln -s $1 $2
fi
}

link ~/.dotfiles/.bashrc ~/.bashrc
link ~/.dotfiles/.tigrc ~/.tigrc
link ~/.dotfiles/bin ~/bin
link ~/.dotfiles/.irssi ~/.irssi
link ~/.dotfiles/.moc ~/.moc
link ~/.dotfiles/.rtorrent.rc ~/.rtorrent.rc
link ~/.dotfiles/bin/byobu ~/.byobu/bin
link ~/.dotfiles/.config/terminator ~/.config/terminator
