#!/bin/sh

projects=(dotfiles lichess exercise symfony2bundles symfony symfony-docs Twig zf2 vimium UserBundle ForumBundle doctrine2 mongodb-odm jquery jquery-ui)
currentdir=$(pwd)
workspace=~/data/workspace

for name in ${projects[@]}
do
    path="$workspace/$name"
    if [ -d $path ]; then
        printf "\n#%s - " $name
        cd $path
        status=$(git status -s)
        if [ "$status" == "" ]; then
            echo "Pulling $name to $path"
            git pull
            git submodule update --init --recursive
        else
            echo "$path is dirty, will only fetch"
            git fetch
        fi
    else
        echo "$path does not exist"
    fi
done

cd $currentdir
echo "Done."
