#!/bin/zsh

projects=(dotfiles lichess exercise symfony2bundles symfony symfony-docs Twig zf2 vimium UserBundle ForumBundle doctrine2 mongodb-odm jquery jquery-ui)
currentdir=$(pwd)
workspace=~/data/workspace

for name in ${projects[@]}
do
    WORKSPACEPATH="$workspace/$name"
    if [ -d $WORKSPACEPATH ]; then
        printf "\n#%s - " $name
        cd $WORKSPACEPATH
        GITSTATUS=$(git status -s)
        if [ -z "$GITSTATUS" ]; then
            echo "Pulling $name to $WORKSPACEPATH"
            git pull
            git submodule update --init --recursive
        else
            echo "$WORKSPACEPATH is dirty, will only fetch"
            git fetch
        fi
    else
        echo "$WORKSPACEPATH does not exist"
    fi
done

cd $currentdir
echo "Done."
