#!/bin/sh

# http://www.linuxfoundation.org/collaborate/workgroups/networking/netem#Examples

# When loss is used locally (not on a bridge or router), the loss is reported to the upper level protocols. This may cause TCP to resend and behave as if there was no loss. When testing protocol reponse to loss it is best to use a netem on a bridge or router

if [ "$1" = "on" ]; then
  echo "slowing local traffic down"
  sudo tc qdisc add dev lo root netem delay 100ms 50ms 50%
  # sudo tc qdisc add dev lo root netem loss 20% 25%
else
  echo "terminate simulation"
  sudo tc qdisc del dev lo root netem delay 100ms 50ms 50%
  # sudo tc qdisc del dev lo root netem loss 20% 25%
fi
