#!/bin/sh

FLAG_FILE=/tmp/sc2-enabled

rm -f ~/dotfiles/i3/config
if grep -q 1 "$FLAG_FILE"; then
  ln -s ~/dotfiles/i3/config.normal ~/dotfiles/i3/config
  echo 0 > $FLAG_FILE
  notify-send "sc2 OFF"
else
  ln -s ~/dotfiles/i3/config.sc2 ~/dotfiles/i3/config
  echo 1 > $FLAG_FILE
  notify-send "sc2 ON"
fi
i3-msg reload
