#!/bin/sh

if [ "$1" = "quiet" ]; then
  mode="Quiet"
elif [ "$1" = "cool" ]; then
  mode="Cool"
elif [ "$1" = 'perf' ]; then
  mode="UltraPerformance"
elif [ "$1" = 'optimized' ]; then
  mode="Optimized"
else
  echo "Expected quiet, cool, perf or optimized"
  exit 1;
fi

echo "Setting ThermalManagement=$mode"

sudo cctk --ThermalManagement=$mode
