#!/bin/bash
i3-msg "workspace 9; append_layout ~/dotfiles/i3/workspace-9.json"

(kitty -1 --title "journal" --hold zsh -c "journalctl -f" &)
(kitty -1 --title "btop" --hold zsh -c "btop" &)
(kitty -1 --title "term" &)
