#! /bin/zsh

# usage: alsa-swap <card-number>

if [ $# -gt 0 ]
then
    card="$1"
else
    card="defaut"
fi

if [ $card = "usb" ]
then
    cardNumber=1
else
    cardNumber=0
fi

echo "defaults.ctl.card $cardNumber" > ~/.asoundrc 
echo "defaults.pcm.card $cardNumber" >> ~/.asoundrc 
echo "defaults.timer.card $cardNumber" >> ~/.asoundrc 

sudo rc.d restart alsa
pkill mpd && sleep 2 && mpd

exit 0
