#!/bin/sh

device="enp0s20f0u$1"
pidfile="/run/dhcpcd-$device.pid"

if [ -f $pidfile ]; then
  echo "Already connected."
else
  sudo modprobe usbnet
  sudo ifconfig $device up
  sudo dhcpcd $device
  echo "Connected!"
fi
