#!/bin/sh

sudo modprobe usbnet

for i in 1 2 3 4 5 6 7 8; do

  device="enp0s20f0u$i"
  pidfile="/run/dhcpcd-$device.pid"

  echo;
  echo $device;
  echo;
  sudo dhcpcd -x $device;

  if [ -f $pidfile ]; then
    echo "Already connected."
  else
    sudo ip link set $device up
    sudo dhcpcd -B $device
    if [ $? -eq 0 ]; then
      sudo cp /home/thib/.scripts/resolv.conf /etc/resolv.conf
      echo "Connected!"
    fi
  fi

done
