#!/bin/zsh

DESTINATION=/media/passport/balrog/

ssh balrog "nice -n 19 rsync --archive --force --delete --progress /home/mongodb /home/backup/"

rsync --archive --force --delete --progress --compress balrog:/home/backup/mongodb $DESTINATION
