#!/bin/zsh

BACKUPDIR=/media/passport/backup-arch/

rsync --archive --force --delete --progress --compress /etc $BACKUPDIR
# rsync --archive --force --delete --progress --compress /usr $BACKUPDIR
#rsync --archive --force --delete --progress --compress /var $BACKUPDIR
