#!/bin/zsh

DESTINATION=~/backup/balrog/
DESTINATION=/media/thib-ext4/balrog/

ssh balrog "rsync --archive --force --delete --progress /home/mongodb /home/backup/"

rsync --archive --force --delete --progress --compress balrog:/home/backup/mongodb $DESTINATION
