#!/bin/zsh

INTERVAL=1
LICHESS_INTERVAL=4
LICHESS_TIMEOUT=3
LICHESS_URL="http://en.lichess.org/status"

calculate_cpu_usage()
{
    DATAFILE="/tmp/cpu_usage_data"
    RESFILE="/tmp/cpu_usage"

    CPU=($(cat /proc/stat | grep '^cpu ')) # Get the total CPU statistics.
    shift CPU
    IDLE=${CPU[4]}                        # Get the idle CPU time.

    # Calculate the total CPU time.
    TOTAL=0
    for VALUE in "${CPU[@]}"; do
        let "TOTAL=$TOTAL+$VALUE"
    done

    if [ -f $DATAFILE ]; then
        set -- $(cat $DATAFILE)
        # Calculate the CPU usage since we last checked.
        let "DIFF_IDLE=$IDLE-$1"
        let "DIFF_TOTAL=$TOTAL-$2"
        let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
        echo $DIFF_USAGE > $RESFILE
    fi

    # Remember the total and idle CPU times for the next check.
    echo "$IDLE $TOTAL" > $DATAFILE
}

fetch_lichess_status()
{
    DATAFILE="/tmp/lichess_status"
    echo $(curl --connect-timeout $LICHESS_TIMEOUT -m $LICHESS_TIMEOUT -s $LICHESS_URL) > $DATAFILE
}


while true; do

    sleep $INTERVAL

    calculate_cpu_usage

    if [ $(($(date +%S) % $LICHESS_INTERVAL)) -eq 0 ]; then
        (fetch_lichess_status) &
    fi

done
