#!/bin/zsh

INTERVAL=1
INTERNET_TIMEOUT=3
LICHESS_INTERVAL=3
LICHESS_LOADTIME_INTERVAL=3
LICHESS_URL="http://en.lichess.org/monitor/status"

fetch_box_status()
{
    DATAFILE="/tmp/box_status"
    ping -c 1 google.com | grep ".net" | wc -l > $DATAFILE
}
fetch_lichess_status()
{
    DATAFILE="/tmp/lichess_status"
    echo $(curl --connect-timeout $INTERNET_TIMEOUT -m $INTERNET_TIMEOUT -s $LICHESS_URL) > $DATAFILE
}
fetch_lichess_loadtime()
{
    DATAFILE="/tmp/lichess_loadtime"
    echo $(ssh -o ConnectTimeout=$INTERNET_TIMEOUT hollie "/usr/bin/time -p wget -p --no-cache --delete-after http://en.lichess.org -q 2>&1 | awk '/^real / { print \$2 }'") > $DATAFILE
}


while true; do

    sleep $INTERVAL

    seconds=$(date +%S)
    
    if [ $((seconds % 3)) -eq 0 ]; then
        (fetch_box_status) &
    fi

    # if [ $((seconds % $LICHESS_INTERVAL)) -eq 0 ]; then
    #     (fetch_lichess_status) &
    # fi
    # if [ $((seconds % $LICHESS_LOADTIME_INTERVAL)) -eq 0 ]; then
    #     (fetch_lichess_loadtime) &
    # fi

done
