#!/bin/zsh

INTERVAL=1
INTERNET_TIMEOUT=3
LICHESS_INTERVAL=4
GMAIL_INTERVAL=20
LICHESS_URL="http://en.lichess.org/status"

get_new_mails()
{
  DATAFILE="/tmp/gmail_status"
  gmail=$(curl --connect-timeout $INTERNET_TIMEOUT -m $INTERNET_TIMEOUT -u $GMAIL_PERSO --silent 'https://mail.google.com/mail/feed/atom' | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n 's/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2 - \1/p' | wc -l)
  jirafe=$(curl --connect-timeout $INTERNET_TIMEOUT -m $INTERNET_TIMEOUT -u $GMAIL_JIRAFE --silent 'https://mail.google.com/mail/feed/atom' | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n 's/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2 - \1/p' | wc -l)
  echo "gmail($gmail) jirafe($jirafe)" > $DATAFILE
}

calculate_cpu_usage()
{
    DATAFILE="/tmp/cpu_usage_data"
    RESFILE="/tmp/cpu_usage"

    CPU=($(cat /proc/stat | grep '^cpu ')) # Get the total CPU statistics.
    shift CPU
    IDLE=${CPU[4]}                        # Get the idle CPU time.

    # Calculate the total CPU time.
    TOTAL=0
    for VALUE in "${CPU[@]}"; do
        let "TOTAL=$TOTAL+$VALUE"
    done

    if [ -f $DATAFILE ]; then
        set -- $(cat $DATAFILE)
        # Calculate the CPU usage since we last checked.
        let "DIFF_IDLE=$IDLE-$1"
        let "DIFF_TOTAL=$TOTAL-$2"
        let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
        echo $DIFF_USAGE > $RESFILE
    fi

    # Remember the total and idle CPU times for the next check.
    echo "$IDLE $TOTAL" > $DATAFILE
}

fetch_lichess_status()
{
    DATAFILE="/tmp/lichess_status"
    echo $(curl --connect-timeout $INTERNET_TIMEOUT -m $INTERNET_TIMEOUT -s $LICHESS_URL) > $DATAFILE
}


while true; do

    sleep $INTERVAL

    calculate_cpu_usage

    seconds=$(date +%S)

    if [ $((seconds % $LICHESS_INTERVAL)) -eq 0 ]; then
        (fetch_lichess_status) &
    fi
    if [ $((seconds % $GMAIL_INTERVAL)) -eq 0 ]; then
        (get_new_mails) &
    fi

done
