#!/bin/sh

DIR=/run/crom
LOG=/var/log/cpu-monitor
mkdir -p $DIR

echo "START" >> $LOG

while :
do
  sens=$(sensors -A)

  temp=$(echo $sens | sed -rn 's/.*Tccd1:\s+.([0-9]+).*/\1/p')
  freqs=$(grep 'cpu MHz' /proc/cpuinfo | cut -c12-15)
  min_freq=$(echo "$freqs" | sort | head -1)
  max_freq=$(echo "$freqs" | sort -r | head -1)
  echo "$min_freq-$max_freq $temp" > $DIR/cpu-monitor

  gpu_power=$(echo $sens | sed -rn 's/.*slowPPT:\s+([0-9]+).*/\1/p')
  gpu_temp=$(echo $sens | sed -rn 's/.*edge:\s+.([0-9]+).*/\1/p')
  echo "$gpu_power $gpu_temp" > $DIR/gpu-monitor

  # if (( "$gpu_power" > 9 )); then
  #   rgboff=0
  #  else
  # fi
  # echo "$rgboff" > /run/crom/rgb-off 

  # if xset q | grep 'Monitor is On' > /dev/null; then
  #   rgboff=0
  # else
  #   rgboff=1
  # fi
  # echo "$rgboff" > /run/crom/rgb-off 


  # DISPLAY=0 xset q
  # monitor_on=$(xset q)
  # # monitor_on=$(xset q)
  # echo "$monitor_on" >> $LOG

  sleep 1
done
