#!/bin/sh

# run me as superuser
# best called from /etc/rc.local

# if the nvidia nouveau module is not loaded,
# disable the nvidia card with acpi_call
if ! lsmod | grep -q nouveau; then
  /home/thib/.scripts/nvidia off
fi
