#!/bin/sh

filename=djiparsetxt-latest.tar.gz
url=http://djilogs.live555.com/public/$filename
dir=~/djiparsetxt

rm -rf $dir
cd ~/tmp
rm djiparsetxt-*
curl -O $url
tar xzf $filename
rm $filename
mv djiparsetxt-* $dir
cd $dir
make
