#!/bin/zsh

REMOTE=$1
DB=$2
COLL=$3
ID=$4
FILE=$DB-$COLL.$ID.export.json

ssh $REMOTE mongoexport --db $DB --collection $COLL -q \'{\"_id\":\"$ID\"}\' --out /root/$FILE
scp $REMOTE:$FILE ./
ssh $REMOTE rm /root/$FILE
mongo $DB --eval "db.$COLL.remove({_id:'$ID'})"
mongoimport --db $DB --collection $COLL $FILE
rm $FILE
