#!/bin/sh

REMOTE=$1
DB=$2
COLL=$3
FILE=$DB-$COLL.export.json
REMOTE_PATH=/home/mongo-export/$FILE

C="ssh $REMOTE mongoexport --db $DB --collection $COLL --out $REMOTE_PATH --limit 1000000"
echo $C

$C

scp $REMOTE:$REMOTE_PATH ./
ssh $REMOTE rm $REMOTE_PATH
mongoimport --db $DB --collection $COLL $FILE
rm $FILE
