#!/usr/bin/zsh

setxkbmap -keycodes evdev us -variant colemak
xmodmap ~/dotfiles/xmodmap/xps
xset r rate 250 56

# touchpad
xinput --set-prop 'DELL098F:00 04F3:311C Touchpad' 'libinput Tapping Enabled' 1
xinput --set-prop 'DELL098F:00 04F3:311C Touchpad' 'libinput Middle Emulation Enabled' 1
xinput --set-prop 'DELL098F:00 04F3:311C Touchpad' 'libinput Accel Speed' 0.2

# 'pointer:Razer Razer DeathAdder 2013' - dup :(
xinput --set-prop 20 'libinput Accel Profile Enabled' 0 1
xinput --set-prop 20 'Coordinate Transformation Matrix' 2.000000, 0.000000, 0.000000, 0.000000, 2.000000, 0.000000, 0.000000, 0.000000, 1.000000
