#!/bin/sh

setxkbmap -keycodes evdev us -variant colemak
xset r rate 200 56

# 'pointer:Razer Razer DeathAdder 2013' - dup :(
# xinput --set-prop 20 'libinput Accel Profile Enabled' 0 1
# xinput --set-prop 20 'Coordinate Transformation Matrix' 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
