#!/usr/bin/zsh

setxkbmap -keycodes evdev us -variant colemak
xmodmap ~/dotfiles/xmodmap/xps15
xset r rate 220 56

# touchpad
xinput --set-prop 'DLL07BE:01 06CB:7A13 Touchpad' 'libinput Tapping Enabled' 1 
xinput --set-prop 'DLL07BE:01 06CB:7A13 Touchpad' 'libinput Middle Emulation Enabled' 1
xinput --set-prop 'DLL07BE:01 06CB:7A13 Touchpad' 'libinput Accel Speed' 0.9
