#!/bin/sh
# Link files to the system
# Needs superuser permissions

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute path this script is in
SCRIPTPATH=`dirname $SCRIPT`

echo "Linking system files from $SCRIPTPATH"

link (){
    FROM="$SCRIPTPATH/../$1"
    TO=$2

    printf "ln -s %s %s\n" $FROM $TO

    rm $TO
    ln -s $FROM $TO
}
