#!/bin/sh

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute path this script is in
SCRIPTPATH=`dirname $SCRIPT`

echo "Linking config files from $SCRIPTPATH"

link (){
    FROM="$SCRIPTPATH/../$1"
    TO=$2

    printf "ln -s %s %s\n" $FROM $TO

    rm $TO
    ln -s $FROM $TO
}

mkdir -p ~/.config

link zshrc ~/.zshrc
link scripts ~/.scripts
link gitconfig ~/.gitconfig
link nvim ~/.config/nvim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mkdir ~/.config/nvim/undodir
link tigrc ~/.tigrc
link rtorrent.rc ~/.rtorrent.rc
link xinitrc ~/.xinitrc
link Xresources ~/.Xresources
link xcolors ~/.xcolors
link mpd ~/.config/mpd
mkdir -p ~/.i3
link i3/config ~/.i3/config
link i3/status ~/.i3/status
mkdir -p ~/.config/dmenu-frecency
link dmenu-frecency.conf ~/.config/dmenu-frecency/config.json
mkdir -p ~/.config/ranger
link ranger/rc.conf ~/.config/ranger/rc.conf
link ranger/apps.py ~/.config/ranger/apps.py
link redshift.conf ~/.config/redshift.conf
link ttytterrc ~/.ttytterrc
link inputrc ~/.inputrc
link editrc ~/.editrc
link ghci ~/.ghci
mkdir -p ~/.ssh
link ssh/config ~/.ssh/config
mkdir -p ~/.config/htop
link htoprc ~/.config/htop/htoprc
mkdir -p ~/.sbt/1.0
link sbt-1.0/global.sbt ~/.sbt/1.0/global.sbt
link sbt-1.0/plugins ~/.sbt/1.0/plugins
link sbtrc ~/.sbtrc
link editorconfig ~/.editorconfig
#link sbt/build.sbt ~/.sbt/build.sbt
link zlogin ~/.zlogin
link alacritty.yml ~/.config/alacritty/alacritty.yml
mkdir -p ~/.bloop
link bloop.json ~/.bloop/bloop.json
mkdir -p ~/.config/mpv
link mpv.conf ~/.config/mpv/mpv.conf

cd mongo-hacker
make
cd -
