#!/bin/sh

server=hanoi
db=lichess

studyIds='Z1DKk4Rl BJy6fEDf Rg2cMBZ6 fE4k21MW 8yadFPpU PDkQDt6u 96Lij7wH 9ogFv8Ac tuoBxVE5 Qj281y1p MnsJEWnI o734CNqp 9cKgYrHb ITWY4GN2 g1fxVZu9 s5pLU7Of xebrDvFe A4ujYOer RUQASaZm';

echo "Fetching practice structure";
~/.scripts/fetch-mongodb-document $server $db flag "practice"

for studyId in $studyIds; do
  echo "Fetching study #$studyId";
  mongo $db --eval "db.study_chapter.remove({studyId:'$studyId'})";
  ~/.scripts/fetch-mongodb-document $server $db study "$studyId";
  query="{studyId:\'$studyId\'}";
  echo $query;
  ~/.scripts/fetch-mongodb-query $server $db study_chapter $query;
done
