#!/usr/bin/env bash

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute path this script is in
SCRIPTPATH=`dirname $SCRIPT`

echo "Linking config files from $SCRIPTPATH"

link (){
    FROM="$SCRIPTPATH/../$1"
    TO=$2

    printf "ln -s %s %s\n" $FROM $TO

    rm $TO
    ln -s $FROM $TO
}

link bashrc ~/.bashrc
link scripts ~/.scripts
link screenrc ~/.screenrc
link byobu/bin ~/.byobu/bin
link byobu/keybindings ~/.byobu/keybindings
link vimrc ~/.vimrc
link vim ~/.vim
link tigrc ~/.tigrc
link irssi ~/.irssi
link moc ~/.moc
link rtorrent.rc ~/.rtorrent.rc
link config/terminator ~/.config/terminator
