#!/bin/zsh
                                                                                                       
FILE=/sys/class/backlight/gmux_backlight/brightness
BACKLIGHT=$(<$FILE)
MAX=$(</sys/class/backlight/gmux_backlight/max_brightness)
MIN=1000
FACTOR=1.5

if [ $UID -ne 0 ]; then
    echo "Please run this program as superuser"
    exit 1
fi

case $1 in

    up)
        (( TDouble = BACKLIGHT * FACTOR ))
        TOTAL=$(echo "$TDouble"|sed "s/\([0-9]*\)\.*.*/\1/")
        if [ $BACKLIGHT -eq $MAX ]; then
                exit 1
        fi
        if [ $TOTAL -gt $MAX ]; then
            let TOTAL=MAX
        fi
        echo $TOTAL > $FILE
        ;;
    down)
        (( TDouble = BACKLIGHT / FACTOR ))
        TOTAL=$(echo "$TDouble"|sed "s/\([0-9]*\)\.*.*/\1/")
        if [ $BACKLIGHT -eq $MIN ]; then
                exit 1
        fi
        if [ $TOTAL -lt $MIN ]; then
            let TOTAL=MIN
        fi
        echo $TOTAL > $FILE
        ;;
    *)
        echo "Use: up|down"
        ;;
esac
