#!/usr/bin/zsh

echo "MPD Radio AdBlock started";

detect() {
  current=$(mpc current);
  if [ $? != 0 ]; then
    echo "mpd is not running, exiting!";
    exit 1;
  fi
  echo "Current song: $current";
  [ "$current" = "FuzzyandGroovy" ] && return 1;
  [ "$current" = "4USmoothJazz" ] && return 1;
  test "${current#*"TSTAG_"}" != "$current" && return 1;
  test "${current#*"There's More To ROCKRADIO.COM!"}" != "$current" && return 1;
  test "${current#*"JINGLE"}" != "$current" && return 1;
  test "${current#*"Annonce"}" != "$current" && return 1;
  test "${current#*"BarockMusic"}" != "$current" && return 1;
  test "${current#*"RadioMozart"}" != "$current" && return 1;
  test "${current#*"Classy"}" != "$current" && return 1;
  return 0;
}

while : ; do
  detect;
  if [ $? -eq 1 ]; then
    echo "AD detected, waiting for confirmation...";
    sleep 1;
    detect;
    if [ $? -eq 1 ]; then
      echo "AD confirmed, switching";
      mpc pause;
      ~/.scripts/radio random &;
    fi
  fi
  sleep 1; # may prevent loop frenzy
  mpc idle;
done
