#!/usr/bin/zsh

if [ ! -f ~/.mpd/mpd.pid ]; then 
  if [ ! -f ~/.mpd/mpd.conf ]; then 
    "No mpd configuration found! Probably not the right user: $(whoami)";
    exit 1;
  fi
  mpd ~/.mpd/mpd.conf > /tmp/mpd.log 2>&1 &;
  sleep 2;
  ~/.scripts/mpd-adblock > /tmp/mpd-adblock.log 2>&1 &;
fi
