#!/usr/bin/zsh

case $1 in
  "down")    do pactl set-sink-volume 0 -4%; done;;
  "up")      do pactl set-sink-volume 0 +4%; done;;
  "toggle")  do pactl set-sink-mute 0 toggle; done;;
  "current") echo "$(playerctl -p spotify metadata artist) - $(playerctl -p spotify metadata album) - $(playerctl -p spotify metadata title)";;
  "copy-current") echo "Current song: $(~/.scripts/music current)" | xclip -selection clipboard;;
  *)
esac
