#!/bin/zsh

case $1 in
    "up")     mpc volume +5 && mpc volume;;
    "down")   mpc volume -5 && mpc volume;;
    "toggle") mpc toggle;;
    "ui")     [ ! -f ~/.mpd/mpd.pid ] && mpd ~/.mpd/mpd.conf 2> /dev/null; ncmpcpp;;
    *)
esac
