#!/usr/bin/zsh

radios=(Random
Fuzzy
Ambiance
AcidJazz
Jazz
Guitar
Piano
Mozart
Barock
Reggae
60sRock
BluesRock
HardRock
HarderRock
DeathMetal
MelodicDeathMetal
ProgressiveMetal
ProgressiveRock
ClassicRock
ClassicMetal
HairBands
BeatlesTribute);

if [ $1 = "random" ]; then
  N=${#radios};
  ((N=RANDOM%N+1));
  radio=${radios[$N]};
else
  IFS=$'\n';
  radios="${radios[*]}";
  source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini;
  radio=$(echo $radios | ~/.scripts/dmenu-dark -p "Rock Radio ");
fi

radio=$radio:l;
echo $radio;

[ -z "$radio" ] && exit;

case $radio in
  "random") ~/.scripts/radio random; exit;;
  "fuzzy") url="http://listen.radionomy.com/fuzzy-and-groovy";;
  "ambiance") url="http://listen.radionomy.com/ambiance-radio";;
  "acidjazz") url="http://listen.radionomy.com/4u-smooth-jazz";;
  "jazz") url="http://listen.radionomy.com/abc-jazz";;
  "guitar") url="http://listen.radionomy.com/acoustic-guitar";;
  "piano") url="http://listen.radionomy.com/piano";;
  "mozart") url="http://listen.radionomy.com/radio-mozart";;
  "barock") url="http://listen.radionomy.com/barock-music";;
  "reggae") url="http://listen.radionomy.com/ambiance-reggae";;
  *) url="http://pub4.rockradio.com:80/rr_$radio";;
esac

~/.scripts/mpd-launcher;
mpc clear;
mpc add $url;
mpc play;
