#!/bin/zsh

radios="Fuzzy
60sRock
BluesRock
HardRock
HarderRock
DeathMetal
MelodicDeathMetal
ProgressiveMetal
ProgressiveRock
ClassicRock
ClassicMetal
HairBands
BeatlesTribute"

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

radio=$(echo $radios | ~/.scripts/dmenu-dark -p "Rock Radio ")
radio=$radio:l

[ -z "$radio" ] && exit

case $radio in
  "fuzzy") url="http://listen.radionomy.com/fuzzy-and-groovy";;
  *) url="http://pub4.rockradio.com:80/rr_$radio";;
esac

~/.scripts/mpd-launcher;
mpc clear;
mpc add $url;
mpc play;
