#!/bin/sh

SET="liquidctl --match kraken set"

case $1 in

  slow-burn)
    $SET ring color fading 550000 aa5500 dd0000 --speed=slower
    $SET logo color fading 550000 aa5500 dd0000 --speed=slower
    ;;

  rage)
    $SET ring color fading 330000 ff0000 --speed=faster
    $SET logo color fading 660000 330000
    ;;

  burn)
    $SET ring color fading 330000 ff0000 ff1100 ff0000
    $SET logo color fading 660000 330000
    ;;

  fusion)
    $SET ring color wings 0000ff 
    $SET logo color fading 000066 333333
    ;;

  rainbow)
    $SET ring color super-rainbow --speed=faster
    $SET logo color fixed 888888
    ;;

  spectrum)
    $SET ring color spectrum-wave --speed=fastest
    $SET logo color fixed 888888
    ;;

  breathing)
    $SET ring color breathing 550000 aa5500 dd0000
    $SET logo color fixed 888888
    ;;

  purple)
    $SET ring color breathing 090050 5500ff
    $SET logo color fixed 100060
    ;;

  purple-burn)
    $SET ring color fading 090020 3300ff 6600ff
    $SET logo color fixed 100060
    ;;

  off)
    $SET ring color fixed 000000
    $SET logo color fading 660000 000000 --speed=fastest
    ;;

  *)
    $SET ring color fixed ffffff
    $SET logo color fixed aaaaaa
    ;;

esac
