#!/bin/zsh

. /etc/profile.d/prll.sh

dest=paul:/home/sacem
base_url=http://sacem.iliaz.com

sendToSacem() {

  orig=$1

  echo "Send $orig to $dest -- $base_url/$1"

  scp $orig $dest
}

prll sendToSacem $@
