#!/bin/sh

scala -cp ~/bin/scalariform_*.jar scalariform.commandline.Main \
+alignSingleLineCaseStatements \
+compactControlReadability \
+doubleIndentClassDeclaration \
+rewriteArrowSymbols \
+preserveDanglingCloseParenthesis \
"$@"
