#!/bin/sh

java -jar ~/.bin/scalariform.jar \
+alignSingleLineCaseStatements \
+compactControlReadability \
+doubleIndentClassDeclaration \
+rewriteArrowSymbols \
+preserveDanglingCloseParenthesis \
--stdout --forceOutput "$@"
