#!/bin/zsh

values=(powersave conservative ondemand performance)
value=$1

if [[ ${values[(r)$value]} == $value ]] ; then 
  echo "Setting cpufreq to $value"
  sudo sed -i "s/governor=\".*\"/governor=\"$value\"/g" /etc/conf.d/cpufreq 
  sudo rc.d restart cpufreq
  echo "cpufreq has been set to $value"
else 
  echo "value must be one of: $values" 
fi
