#!/bin/zsh

startcommands=()

echo "1 - Raw shell"
startcommands[1]="zsh"

echo "2 - New session"
startcommands[2]="tmux"

it=3
tmuxinatorpath="$HOME/.tmuxinator/"
for scriptpath in "$tmuxinatorpath"[a-z]*.tmux; do
	script=$(basename "$scriptpath")
    name=$(echo "$script" | sed "s/.tmux//")
    printf "%d - %s\n" $it "${(C)name}"
    startcommands[$it]="$scriptpath"
    it=$(expr $it + 1)
done

echo "------------------"
read choice

startcommand=$startcommands[$choice]

clear
if [ -f $startcommand ] && [ ! -x $startcommand ]; then
    source $startcommand
else
    $startcommand
fi
