#!/bin/zsh

startcommands=()

separator="--------------------------------"
lines=$separator

lines="$lines\n1 - Raw shell"
startcommands[1]="zsh"

lines="$lines\n2 - New session"
startcommands[2]="tmux"

it=3
tmuxinatorpath="$HOME/.tmuxinator/"
for scriptpath in "$tmuxinatorpath"[a-z]*.tmux; do
    name=$(basename $scriptpath | sed "s/.tmux//")
    lines="$lines\n$it - ${(C)name}"
    startcommands[$it]="$scriptpath"
    it=$(expr $it + 1)
done

lines="$lines\n$separator"
echo -e "$lines"

read choice
startcommand=$startcommands[$choice]

clear
if [ -f $startcommand ] && [ ! -x $startcommand ]; then
    source $startcommand
else
    $startcommand
fi
