#!/bin/sh

# most code from https://github.com/linrunner/TLP/blob/master/tlp-stat.in

readonly CORETEMP_DIRS="
/sys/devices/platform/coretemp.0
/sys/devices/platform/coretemp.0/hwmon/hwmon*"
readonly HWMONFAN_DIRS="
/sys/class/hwmon/hwmon*/device
/sys/class/hwmon/hwmon*"

glob_files () {
  [ -n "${1-}" ] || return 64
  local glob_pattern file_iter

  glob_pattern="${1}"

  while shift && [ $# -gt 0 ]; do
    for file_iter in ${1}${glob_pattern}; do
      [ ! -f "${file_iter}" ] || echo "${file_iter}"
    done
  done
}

# --- show temperatures
echo "+++ Temperatures"
# use sensors
cmax=0
for sens in $(glob_files '/temp?*_input' $CORETEMP_DIRS); do
  if grep -q -- 'Physical' ${sens%input}label 2>/dev/null; then
    # package info is available -> ignore remaining sensors
    read -r cmax < $sens
    break
  else
    echo $sens
    cat $sens
    # core info -> find max value
    read -r ctemp < $sens && [ $ctemp -gt $cmax ] && cmax=$ctemp
  fi
done
if [ $cmax -gt 0 ]; then
  perl -e 'printf ("CPU temp               = %5d [°C]\n", '$cmax' / 1000.0);'
fi

# --- show fan speed
# use hwmon
have_any_fan=
for fan in $(glob_files '/fan?*_input' $HWMONFAN_DIRS); do
  if read -r fan_speed < $fan; then
    fan_name="${fan##*/}"; fan_name="${fan_name%_input}"
    have_any_fan=y

    echo $fan
    printf "Fan speed (%s)       = %5d [/min]\n" \
      "${fan_name}" "${fan_speed}"
  fi
done
if [ -z "${have_any_fan}" ]; then
  printf "Fan speed              = (not available)\n"
fi
echo
