#!/usr/bin/env bash

projects=(dotfiles lichess exercise symfony2bundles symfony symfony-docs Twig zf2 vimium DoctrineUserBundle ForumBundle doctrine2 mongodb-odm jquery jquery-ui)
currentdir=$(pwd)
workspace=~/data/workspace

for name in ${projects[@]}
do
    path="$workspace/$name"
    echo "Pulling $name to $path"
    cd $path
    git pull
    git submodule update --init --recursive
done

cd $currentdir
