#!/bin/sh

DIR="/proc/acpi/thermal_zone"

i=/sys/class/hwmon/hwmon0/temp1_input
[ -s "$i" ] && t=$(awk '{printf "%0.f",$1/1000}' "$i")
if [ -n "$t" ]; then
	if [ "$t" -gt 64 ]; then
        modifier="#[bg=red,fg=white,bright]"
	elif [ "$t" -gt 59 ]; then
        modifier="#[fg=red,bright]"
	elif [ "$t" -gt 54 ]; then
        modifier="#[fg=magenta,bright]"
	elif [ "$t" -gt 49 ]; then
        modifier="#[fg=cyan]"
	else
        modifier="#[fg=blue]"
	fi
    echo "$modifier$t°C#[default]"
fi
