#!/bin/zsh

projects=$(ls -l ~/.tmuxinator/| grep "^-" | awk {'print $9'} | cut -d. -f1)

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

project=$(echo $projects | /home/thib/dotfiles/scripts/dmenu-dark -p "TMUX workspace ")

[ -z "$project" ] && exit

mux "$project"
