#!/bin/zsh

tmuxinatorpath="$HOME/.tmuxinator/"

ratmenu -fg "#00ff22" -bg "#444444" -style dreary -shell /bin/zsh \
    media "source $tmuxinatorpath/media.tmux" \
    lichess "source $tmuxinatorpath/lichess.tmux" \
    workspace "source $tmuxinatorpath/workspace.tmux" \
    scalex "source $tmuxinatorpath/scalex.tmux" \
    scala-elasticsearch "source $tmuxinatorpath/scala-elasticsearch.tmux" \
    aichallenge "source $tmuxinatorpath/aichallenge.tmux" \
