#!/usr/bin/env zsh

alias japp1="ssh -A japp1"
alias japp2="ssh -A japp2"
alias jdb01="ssh -A jdb01"
alias jdb02="ssh -A jdb02"
alias jdev="ssh -A jdev"
alias jsdb01="ssh -A jsdb01"
alias jsapp1="ssh -A jsapp1"
alias jtest="ssh -A jtest"
alias jproduct="ssh -A jproduct"
alias jfreebird="ssh -A jfreebird"
alias jfbqa="ssh -A jfbqa"
alias marty="export TERM=rxvt-256color && ssh -A marty -t tmux attach"
alias phobos="export TERM=rxvt-256color && ssh phobos -t tmux attach"
alias balrog="export TERM=rxvt-256color && ssh balrog -t tmux attach"
alias hollie="export TERM=rxvt-256color && ssh hollie -t tmux attach"
alias cook="export TERM=rxvt-256color && ssh cook -t tmux attach"
